// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	bus "levelup/internal/platform/bus"

	mock "github.com/stretchr/testify/mock"
)

// MockBus is an autogenerated mock type for the Bus type
type MockBus struct {
	mock.Mock
}

type MockBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBus) EXPECT() *MockBus_Expecter {
	return &MockBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, e
func (_m *MockBus) Publish(ctx context.Context, e bus.Envelope) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bus.Envelope) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - e bus.Envelope
func (_e *MockBus_Expecter) Publish(ctx interface{}, e interface{}) *MockBus_Publish_Call {
	return &MockBus_Publish_Call{Call: _e.mock.On("Publish", ctx, e)}
}

func (_c *MockBus_Publish_Call) Run(run func(ctx context.Context, e bus.Envelope)) *MockBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bus.Envelope))
	})
	return _c
}

func (_c *MockBus_Publish_Call) Return(_a0 error) *MockBus_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBus_Publish_Call) RunAndReturn(run func(context.Context, bus.Envelope) error) *MockBus_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, s
func (_m *MockBus) Subscribe(ctx context.Context, s bus.Subscription) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bus.Subscription) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - s bus.Subscription
func (_e *MockBus_Expecter) Subscribe(ctx interface{}, s interface{}) *MockBus_Subscribe_Call {
	return &MockBus_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, s)}
}

func (_c *MockBus_Subscribe_Call) Run(run func(ctx context.Context, s bus.Subscription)) *MockBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bus.Subscription))
	})
	return _c
}

func (_c *MockBus_Subscribe_Call) Return(_a0 error) *MockBus_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBus_Subscribe_Call) RunAndReturn(run func(context.Context, bus.Subscription) error) *MockBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBus creates a new instance of MockBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBus {
	mock := &MockBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
