// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"myapp/internal/config"
)

// Injectors from wire.go:

// InitializePlatform builds everything below Deps (PRD §7.2): Wire owns the
// infrastructure graph and the reverse-order cleanup chain; module selection
// stays hand-written in registry.go.
func InitializePlatform(ctx context.Context, cfg config.Config) (*Platform, func(), error) {
	telemetry, cleanup, err := provideTelemetry(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := provideDB(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gormDB, err := provideGorm(db, telemetry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	core := provideRedisCore(cfg)
	cache := provideRedisCache(cfg)
	bus := provideBus()
	clock := provideClock()
	store := provideOutbox(clock)
	validator := provideValidator()
	enforcer, cleanup3, err := provideEnforcer(gormDB, core, telemetry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	auth := provideAuthn(cfg, core, clock, telemetry)
	idempotencyStore := provideIdempotency(db)
	limiter := provideLimiter(core)
	platform := &Platform{
		Cfg:        cfg,
		Tel:        telemetry,
		DB:         db,
		Gorm:       gormDB,
		RedisCore:  core,
		RedisCache: cache,
		Bus:        bus,
		Outbox:     store,
		Clock:      clock,
		Validate:   validator,
		Authz:      enforcer,
		Authn:      auth,
		Idem:       idempotencyStore,
		Limiter:    limiter,
	}
	return platform, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
