// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	authz "levelup/internal/platform/authz"

	mock "github.com/stretchr/testify/mock"
)

// MockEnforcer is an autogenerated mock type for the Enforcer type
type MockEnforcer struct {
	mock.Mock
}

type MockEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnforcer) EXPECT() *MockEnforcer_Expecter {
	return &MockEnforcer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, p, perm, resource
func (_m *MockEnforcer) Authorize(ctx context.Context, p authz.Principal, perm authz.Permission, resource any) error {
	ret := _m.Called(ctx, p, perm, resource)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, authz.Principal, authz.Permission, any) error); ok {
		r0 = rf(ctx, p, perm, resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnforcer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockEnforcer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - p authz.Principal
//   - perm authz.Permission
//   - resource any
func (_e *MockEnforcer_Expecter) Authorize(ctx interface{}, p interface{}, perm interface{}, resource interface{}) *MockEnforcer_Authorize_Call {
	return &MockEnforcer_Authorize_Call{Call: _e.mock.On("Authorize", ctx, p, perm, resource)}
}

func (_c *MockEnforcer_Authorize_Call) Run(run func(ctx context.Context, p authz.Principal, perm authz.Permission, resource any)) *MockEnforcer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authz.Principal), args[2].(authz.Permission), args[3].(any))
	})
	return _c
}

func (_c *MockEnforcer_Authorize_Call) Return(_a0 error) *MockEnforcer_Authorize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnforcer_Authorize_Call) RunAndReturn(run func(context.Context, authz.Principal, authz.Permission, any) error) *MockEnforcer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnforcer creates a new instance of MockEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnforcer {
	mock := &MockEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
